### ISSUE TITLE
Web Test Failure Alerts Contain SocketException Stack Trace from Testing Agent

### ISSUE THREAD

**Issue by bobmclaren** [microsoft/ApplicationInsights-Home#57] opened 2016-08-24 13:48 UTC
We had a site go offline due to an outage at our ISP, making the web site unreachable.  I received a Web Test alert for this, but it contained a stack trace.  Initially I was confused, thinking the stack trace was coming from my code, but it's actually a stack trace form the web test agent code, which seems like it doesn't belong in an email alert.  Web test result breakdown provided below:

```
1 primary requests, 0 dependant requests and 0 conditional rules failed

Exception (subtype 'SocketException') occured at 08/24/2016 08:59:10 (UTC) for Uri '[REDACTED URL]', step #1 with the error 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [REDACTED IP]:443', exception text 'System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [REDACTED IP]:443 at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult 
```

**Comment by SergeyKanzhelev** [comment] 2016-08-24 16:19
@SoubhagyaDash, can you please look at it.

**Comment by SoubhagyaDash** [comment] 2016-08-24 17:11
@bobmclaren Not sure I understand. The stack trace is indeed from the test agent, showing that it was not able to connect to your application. If the app had been available, and the test failed for other reasons, it would not have been a stack trace from the agent., it would contain the information as returned by your app, or information on the specific validation rule that failed. We hope that this detail would make it simpler for you to understand the root cause of the alert. Does this help?

**Comment by bobmclaren** [comment] 2016-08-24 17:25
I understand what your saying, but to me this seems out of place.  Providing stack traces from _my_ code is certainly helpful, but if a web test fails, I would not expect to see a test agent stack trace.  That inner plumbing should be hidden away and none of my business.  It should simply provide details of the failed connection.  Knowing what function call in the AI test agent the exception occurred on is not actionable information for me.

**Comment by TimothyMothra** [comment] 2020-04-07 23:37
I'm closing this ticket as out of date.
If you're still having issues, please reopen.

**Closed by TimothyMothra** 2020-04-07 23:37 UTC
Labels: enhancement, prod:webtests
