### ISSUE TITLE
User-Agent not in contexttagkeys, allow to override the browser version field from SDK

### ISSUE THREAD

**Issue by jjjordanmsft** [microsoft/ApplicationInsights-Home#160] opened 2017-08-27 06:56 UTC
The data collector accepts "ai.user.userAgent" as a tag, and the value (after being interpreted) shows up in the portal as the browser version, but it's not included in the current bond schema found here.  Is there another field that ought to be used, or was it removed by accident?

**Comment by SergeyKanzhelev** [comment] 2017-08-28 15:57
This is by design. The idea is that we OK to parse user agent when it is for client side events like `PageView` from browser. Also in this case user agent is very important for telemetry.

For server side events it's rarely useful for triage and diagnostics and we do not want to parse it.

That's said - from historical perspective it was made when billing worked by # of events, not size so it was even worse. We sent a big string just to parse out a bit of information most people not even looked at.

**Comment by SergeyKanzhelev** [comment] 2017-08-28 16:01
Another issue is to expose the browser version field to allow SDK to override it. That probably should be made for all schema fields like country, etc, not only browser version.

**Comment by jjjordanmsft** [comment] 2017-08-28 22:31
Thanks, Sergey.  From a use-case perspective, it makes sense.  But I'd point out that it's been common practice among some web server admins for decades to log the user-agent.  See the [NCSA Combined Log Format](http://www.loganalyzer.net/log-analyzer/apache-combined-log.html).  [NGINX logs it by default](https://www.nginx.com/resources/admin-guide/logging-and-monitoring/), Apache does not but calls it out one that does as a "[commonly used log format](https://httpd.apache.org/docs/2.4/logs.html)".

I understand that SDK users can send it in a custom property if it's not supported.  I just wanted to confirm.

**Comment by SergeyKanzhelev** [comment] 2017-08-29 03:43
From logging perspective customer properties works just fine.

**Comment by TimothyMothra** [comment] 2020-04-07 23:39
I'm closing this ticket as out of date.
If you're still having issues, please reopen.

**Closed by TimothyMothra** 2020-04-07 23:39 UTC
Labels: prod:schema
