### ISSUE TITLE
operation_id not present in DocumentDB dependency call entries

### ISSUE THREAD

**Issue by sabbadino** [Microsoft/ApplicationInsights-Home#84] opened 2017-01-25 09:34 UTC
According to this doc 
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-dependencies
DocumentDB calls are logged as DepencyCalls .. however these entries do not retain the operation_id 

a query like this returns nothing

 dependencies
    | join (requests)
      on operation_Id

**Comment by SergeyKanzhelev** [comment] 2017-01-25 17:41
Thanks for reporting!

I think the root cause is this issue we are tracking in server SDK repo: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/113

Is your application Web API or MVC? Consider using [this](http://apmtips.com/blog/2017/01/05/manual-correlation-in-asp-dot-net-mvc-apps/) approach to correlate requests to async operations in MVC and Web API apps.

**Comment by SergeyKanzhelev** [comment] 2017-01-25 17:42
I'm closing the issue for now - feel free to re-open if you have more questions or feedback. Again, thanks for reporting

**Closed by SergeyKanzhelev** 2017-01-25 17:42 UTC
