### ISSUE TITLE
Process improvement for making bond changes (require bond builds to merge PRs?)

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-Home#205] opened 2018-04-11 20:34 UTC
Hi Core SDK Folks,

In this email I am flagging an issue with dealing with making bond updates.
I do not have to do this often, and I will am OK with however you choose to prioritize and address this (or not). My goal is merely to bring this to your attention and to make a suggestion:

My goal was to add a single field to `DataPoint.bond`. I was following the existing process that Sergey also recently [brought ](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/schema-generation.md)to paper.
After making changes in the Home repo as required, I went to the DotNet repo and run the `generateSchema.ps1` tool.
One of the things the tool does is to copy bond files from the Home repo into the appropriate local repo folder.
This resulted in two surprises of varying degree of unpleasantness:

1.	I discovered that a bunch of changes were copied that I did not make. Some of them, over a year old.
After thinking about it, I realized that this is OK. After all, I also made changes, and I am immediately applying them to the .Net SDK and not to other SDKs (we can do this as a later time).
**Suggestion**: It would be great if the `generateSchema.ps1` tool would support a filter for what it copies. I can use source control to find and undo all the changes I do not want, but they are embedded into several files. It’s wasted work.

1.	Some of these old changes are _invalid_ bond changes. E.g., I discovered at least two. One was very recent and I worked with the author to fix it. Another is over a year old, where in `RemoteDependencyData.bond`, it says: “`120: nullable<bool> 	 success = true;`” (previously this field was non-nullable). However, the [bond spec](http://microsoft.github.io/bond/manual/bond_cs.html#nullable-types) clearly says: “_The default value for a field of a nullable type is always implicitly set to null. Explicit default values for nullable fields are not supported_.”
I think this is not OK. We should have a process that ensures that any changes made to Bond in the Home repo can be built successfully.
**Suggestion**: Require some kind of successful bond build before approving PRs in Hope repo that touch Bond files.
Note: Undoing these changes in the DotNet repo will allow me to work around this, but the problem is that it will never work, and this will need to be a permanent workaround until the original issue is fixed.

**Comment by SergeyKanzhelev** [comment] 2018-04-11 21:55
Feel free to contribute. Both are great suggestions! The issue is we do not have enough time to make improvements in this process. And since it was not happening too often - it was OK to keep it this way. You can see that our bond generator tool is a mess and need a little bit of love as well.

**Comment by macrogreg** [comment] 2018-04-12 01:49
Totally get the lack of time issue. :)
Given that these things happen, indeed, not very often, one option of how we could do (2) is to require that people manually import the updated bond into the .NET SDK and get a clean build. They do not need to push that import to the .NET Repo. Just get a clean build. That would make sure that the updated bond is valid. But it's just an idea, I 'll let you decide. :)

**Comment by SergeyKanzhelev** [comment] 2018-04-12 15:53
Sounds good. Please send PR for schema modification instructions. I agree that as a minimum it may be addressed by clear steps description.

**Comment by TimothyMothra** [comment] 2020-04-07 23:43
I'm closing this ticket as out of date.
If you're still having issues, please reopen.

**Closed by TimothyMothra** 2020-04-07 23:43 UTC
