### ISSUE TITLE
Azure extension causing incomplete HTML response

### ISSUE THREAD

**Issue by NoahStahl** [microsoft/ApplicationInsights-Home#277] opened 2018-10-29 23:04 UTC
We recently started noticing instances of our Azure web apps (asp.net core 2.0 and 2.1) randomly return partial HTML, clipped off at various places in the document. When inspecting the HTML returned (with 200 status), you'd see the HTML just stop at some point. This happens for between 1-20% of requests, seemingly randomly, simply by refreshing page over and over. The majority of requests return successfully.

After narrowing down differences between apps exhibiting this behavior and not, it appears the presence of Application Insights extension v2.6.5 is correlated. If I uninstall the extension, the behavior stops, and 100% of requests are complete. Upon reinstalling the extension, the behavior returns. This would suggest the extension is breaking off the response in some cases, albeit without any known variable condition.

The location of the break in HTML seems to correspond to tag helper tags (including the out of box ones like <a>). It may break elsewhere, but often there.

We also have the Application Insights SDK installed in web project (2.5.1).

The current apparent workaround is to uninstall the AI web app extension. 

Example of returned HTML (about a third of page actual expected content):

![image](https://user-images.githubusercontent.com/7528994/47881623-e5f2a800-dde3-11e8-8584-255395de4ddf.png)

**Comment by NoahStahl** [comment] 2018-11-01 21:34
Wanted to add repro steps in case anyone at Microsoft wants to pursue this. I can reproduce as follows:

1. Create a stock app service in Azure. Running on Windows host. Choose to enable Application Insights integration during setup, which should enable the associated extension (v 2.6.5 as of writing) on the created web app.
2. Create a default aspnet core 2.1 web project in Visual Studio, using the out of box template.
3. From Visual Studio, use the wizard to Add Application Insights telemetry. This puts the SDK into the project.
4. Update all Nuget packages. Gets you to Application Insights 2.5.1 package as of this writing.
5. Publish directly to Azure from Visual Studio.
6. On published site, refresh the page repeatedly. Note the inconsistent responses. Some pages whole, others broken off at certain places.

This certainly appears to be a problem interaction between Application Insights extension and SDK. No code or settings other than defaults and templates.

**Comment by Dmitry-Matveev** [comment] 2018-11-01 23:16
@iusafaro, can this be related to a re-write modification to add JS SDK on-the-fly (is it still on in the extension 2.6.5)? If yes, do you know who would be the owner of that feature to investigate? As per description, the issue is expected to have quite an impact across all customers (at least those on MVC).

**Comment by SergeyKanzhelev** [comment] 2018-11-06 06:59
@iusafaro any updates? + @Mikhail-Pranovich

@NoahStahl is there app setting `APPINSIGHTS_JAVASCRIPT_ENABLED` set on the site?

**Comment by SergeyKanzhelev** [comment] 2018-11-06 06:59
What version of Visual Studio is used?

**Comment by NoahStahl** [comment] 2018-11-06 19:00
Hi @SergeyKanzhelev, the repro steps I used are above. This was using Visual Studio version 15.8.7. Are you able to try repro steps on your end? App settings result from literally the default creation of a new web app in the portal. Based on what I'm seeing, there's nothing specific to my environment here. But would like to have somebody else try.

**Comment by SergeyKanzhelev** [comment] 2018-11-14 19:11
@NoahStahl sorry for delay. I cannot repo this. Do you have `APPINSIGHTS_JAVASCRIPT_ENABLED` set in app settings? Do you have JS snippet embedded when page loaded fine?

![image](https://user-images.githubusercontent.com/9950081/48506346-1718a280-e7fe-11e8-8d4d-cfa0eb2519a3.png)

**Comment by FrederickRies** [comment] 2018-11-21 20:18
Hello all,

We have the exact same behavior on our .NET core 2.1 application targeting the netcoreapp2.1 framework.
The response of the application is truncated randomly.

We use the default packages provided with the ASP.NET core app (Microsoft.AspNetCore.All) in version 2.1.5.
The only package relative to ApplicationInsights is Microsoft.AspNetCore.ApplicationInsights.HostingStartup in version 2.1.1.
We are not using any explicit configuration of AppliationInsights within the app.

The result is the same with the Azure Web App ApplicationInsights extension in version 2.6.5 or with the new ApplicationInsights experience from which I did not see any active extension in the Web App.
We have to desactivate ApplicationInsights or uninstall the extension to make things working again.

**Comment by FrederickRies** [comment] 2018-11-22 09:09
To provide further details, only content generated from Razor views is impacted, our API's with json outputs work properly.

**Comment by lmolkova** [comment] 2018-11-27 03:00
I'm able to repro the issue when APPINSIGHTS_JAVASCRIPT_ENABLED  is set to true. However, by default, this env var is not set by extension.

@FrederickRies, @NoahStahl  could you please check whether APPINSIGHTS_JAVASCRIPT_ENABLED is set (and if the value is true)?

Removing env var or setting it to false mitigates the issue. Also, this env var is not needed on AspNetCore app.

**Comment by NoahStahl** [comment] 2018-11-27 20:37
Hi @lmolkova thanks for looking into it. I'd rather not continue to participate in this testing, since I've detailed the exact repro steps I used -- all defaults, literally, out of box, nothing set by me. It seems pretty clear that there is a bug in the extension since you and others confirm, so that seems sufficient at this point for the devs to try to fix it. I don't see why it's relevant to discuss whether it arises for default settings or not. Thanks!

**Comment by lmolkova** [comment] 2018-11-27 21:11
@NoahStahl we are on the same page here - there is a bug and we are trying to investigate and fix it. 

Having such a bug by default on AspNetCore is not acceptable.

We found one way to reproduce it and we are trying to understand if there are other cases we miss. 

Unfortunately I cannot reproduce the error based on your description, so I probably miss something. If you can help me by having a quick look into app settings, i'd really appreciate it.

**Comment by FrederickRies** [comment] 2018-11-28 08:18
Hello @lmolkova, I can confirm to you that this option is activated for us. The old assistant create this entry when we select "Track client side error" or something like that. So it can be considered as a default option.

Is this option is still an option, because the new assistant in the Azure portal have not something similar ?

I've just made some test on one application and when we activate Application Insights, this setting when is setted to "true" causes this problem .
I will make further test tonight on our main production application.

**Comment by FrederickRies** [comment] 2018-11-29 09:54
We have switched off the APPINSIGHTS_JAVASCRIPT_ENABLED in all our applications and everything is fine.
The option was trully the causes of our issues.

**Comment by lmolkova** [comment] 2018-11-29 17:57
@FrederickRies thanks for the update! and great to know it works for you now.
We are trying to understand why and when this option was set by default and identify components responsible for it. Can you recall when was you AppInsights resource was created and when you installed extension approximately?

Thanks!

**Comment by FrederickRies** [comment] 2018-11-30 13:19
You're welcome.
I think i was not clear. This was not a option activated by default. It was an option that we deliberately activated through the Application Insight blade in our Web App. This was with extension version 2.6.5 and the option was activated at the beginning of october.

**Comment by NoahStahl** [comment] 2018-11-30 16:48
Just confirming: APPINSIGHTS_JAVASCRIPT_ENABLED is a valid configuration setting with either value. Regardless of the value, responses should not be corrupted. Correct?

**Comment by MS-TimothyMothra** [comment] 2019-03-06 23:15
Referencing #282
@cijothomas is working on a fix for this issue.

**Comment by cijothomas** [comment] 2019-03-07 04:11
Fix is deployed to handle this issue in .net core 2.0 and 2.1 apps. Fix for 2.2 (and support for 2.2 apps) is going to be deployed this week/next.

**Comment by cijothomas** [comment] 2019-03-08 15:37
close-this.

**Comment by cijothomas** [comment] 2019-03-08 15:37
please-close

**Comment by cijothomas** [comment] 2019-03-08 15:38
obviously that didn't work 🤦‍♂️

**Comment by TimothyMothra** [comment] 2020-04-08 00:11
I'm closing this ticket as out of date.
If you're still having issues, please reopen.

**Closed by TimothyMothra** 2020-04-08 00:11 UTC
Labels: bug, prod:azrue-appservice-extension
