### ISSUE TITLE
2.4 Dependencies Correlation Broken

### ISSUE THREAD

**Issue by federicobarera** [Microsoft/ApplicationInsights-Home#136] opened 2017-07-19 03:49 UTC
Hi,

I have noticed that upgrading from 2.2 to 2.4 the correlation tracking is lost:

**-> Microsoft.ApplicationInsights.Web 2.2.0 -> Portal -> Search (Requests Only) :**

![image](https://user-images.githubusercontent.com/6658124/28349890-d202dea0-6c88-11e7-9b68-69f23339bc5a.png)

**-> Microsoft.ApplicationInsights.Web 2.4.0 -> Portal -> Search (Requests Only) :**

![image](https://user-images.githubusercontent.com/6658124/28349915-f49e8e6e-6c88-11e7-8467-1c12244b3441.png)

**Comment by cijothomas** [comment] 2017-07-19 20:51
Can you give more specific details about the scenario.
What kind of application is this? What are the dependencies - are they SQL? Http? Are they called async?
Do you have profiler installed via Status Monitor/Azure Extension?
(2.4 version contains lot of changes to improve the correlation , but its not clear whats broken here. so any additional details/small repro code would help us.)

**Comment by federicobarera** [comment] 2017-07-26 23:31
Hi, sorry for late response. 
Let me try to clear up the picture:

The application where AI is hosted is a Web Application, running framework 4.5.2
The dependency type is "WCF" even tho the connection is not performed by the standard wcf service client.
To give you a bit of background, we are using the Microsoft.Sharepoint.Client.ClientContext to communicate with office365 sharepoint instances. The dialect is [Client Object Model](https://msdn.microsoft.com/en-us/library/ff798388.aspx).

Opening the internals of the Sharepoint Client I can see that it doesn't even use an HttpClient, rather creates a raw WebRequest to a .svc endpoint.

@lmolkova 
When following some topics about the DiagnosticSource, it seems that the Diagnostic events were triggered by a DelegatingHandler inside of the HttpClient, so I assume the entire tracking infrastructure is skipped if requests are generated via `System.Net.WebRequest.Create`.

The client is invoked inside of an async block even tho the Sharepoint client itself does not support real async, as the internals perform the call the following way
`public override void Execute()
    {
      this.m_webRequest.GetRequestStream().Close();
      this.m_webResponse = (HttpWebResponse) this.m_webRequest.GetResponse();
    }`

I am not aware of any Status Monitor/Azure Extension installed on top of what is scaffolded by default from the nuget package.

Cheers,

F

**Comment by lmolkova** [comment] 2017-07-26 23:37
@federicobarera 
There are different implementations of HttpClient: .Net Core and .NET Desktop.
.NET Core HttpClient does not use WebRequests internally and diagnostics for it is implemented with DelegatingHandler.

.NET Desktop HttpClient is based on WebRequests and the diagnostics is implemented as a [reflection hook ](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/HttpHandlerDiagnosticListener.cs)

It works for HttpWebRequests as long as the response is properly disposed. Please check if you dispose responses and response streams.

**Comment by federicobarera** [comment] 2017-07-27 05:32
From what I can see inside of the Microsoft.SharePoint.Client.Runtime.dll

Microsoft.SharePoint.Client.ClientRequest and ClientRuntimeContext are correctly closing the response stream after usage.

**Comment by lmolkova** [comment] 2017-07-27 15:35
@federicobarera 

1. Are you sure it uses HttpWebRequest (i.e. System.Net.WebRequest.CreateHttp) and not something else?
2. It would be great if you could provide us with repro code with Sharepoint client

**Comment by federicobarera** [comment] 2017-07-27 23:11
@lmolkova @cijothomas 

Hi, before answering the questions lemme clarify something that it's definitely not clear from my initial post.
Those WCF depedencies **are** tracked by AI, what is lost is the correlation between the initial request to our endpoint and the subsequent calls to Sharepoint. I can still see those calls tracked as "dependency" in the search area, but they aren't anymore related to an initiating "request" to our api.

I do believe so that the AI tracking infrastructure is correctly working, but the correlation information is lost somehow (between 2.2 and 2.4).

To your questions:

1. Yes. it is a web request
(unfortunately the classes seems not be open source, so I had to decompile them)
`Microsoft.SharePoint.Client.SPWebRequestExecutor`

`this.m_webRequest = (HttpWebRequest) System.Net.WebRequest.Create(requestUrl);`
`...`
`this.m_webRequest.GetRequestStream().Close();`
`this.m_webResponse = (HttpWebResponse) this.m_webRequest.GetResponse();`
`...`
`if (this.m_webResponse == null)
        return;
this.m_webResponse.Close();`

2. Regarding a code sample it could be a bit tricky to replicate as you will also need an office 365 sharepoint site. I'll try to set up something in the weekend. 

Cheers

**Comment by lmolkova** [comment] 2017-07-28 16:27
@federicobarera 
I see, so requests and dependencies are tracked, but not correlated. Probably in this case we don't really need the repro code. 

How do you check if they are correlated?

1. Could you try to find some request that has dependency call find it's operation Id  (e.g. in Analytics run `requests | where timestamp >= ago(10m)` and copy operation_Id field ) , 
2. Then run another query in Analytics: `dependencies | where operation_Id == <request-operation-id>`

Do you see any dependencies this way?

**Comment by federicobarera** [comment] 2017-07-29 04:59
Very weird...

In 2.3 dependencies are not visible in the search UI, but I can find them in analytics:
![image](https://user-images.githubusercontent.com/6658124/28742206-427f774c-746d-11e7-8e1e-85ecd9d1a2ae.png)
![image](https://user-images.githubusercontent.com/6658124/28742216-59727440-746d-11e7-9e50-cfd225324b7b.png)

In 2.4 the call and the dependencies are completely unrelated. The only way see what is going on is to click on "All available telemetry 5 minutes before and after"

![image](https://user-images.githubusercontent.com/6658124/28742252-70c6b254-746e-11e7-8356-60756006bf6a.png)

**Comment by lmolkova** [comment] 2017-07-31 16:38
@federicobarera 
do I understand correctly that with 2.4 SDK, if you run query `dependencies | where operation_Id == <request-operation-id>` in Analytics, you do not see any dependencies? (Assuming the request was one that supposed to cause dependencies calls)

Could you please find manually request and dependency that should be related to this request and post here following data:
`operation_Id`, `operation_ParentId`, and `Id` for both: request and dependency telemetry. 
If you have more than one dependency for the same request, please post Ids for 2 dependencies.

It would really help to understand the problem better.

**Comment by federicobarera** [comment] 2017-08-02 23:08
Yes, the understanding is correct.
For the same call:

2.2 -> Dependencies are found in the Search Portal Panel and in Analytics
2.3 -> Dependencies are not found in Search Portal but found in Analytics ( where operation_id == [request-operation-id]
2.4 -> Dependencies are not found in Search Portal neither in Analytics.

Sample request in 2.4:

**Request**:
operationId: adjnj3Y7QuA=
parentId: adjnj3Y7QuA=

**WCF Dependency 1:**
operationId: bbba7b76-4a3ade7e1f0d1840
parentId: bbba7b76-4a3ade7e1f0d1840

**WCF Dependency 2:**
operationId: bbba7b7e-4a3ade7e1f0d1840
parentId: bbba7b7e-4a3ade7e1f0d1840

Http Dependency 1:
operationId: bbba7b7f-4a3ade7e1f0d1840
parentId: bbba7b7a-4a3ade7e1f0d1840

... and so on

**Comment by lmolkova** [comment] 2017-08-03 16:43
@federicobarera

Thanks for the details.

So it seems that asynchronous context is lost after the request processing starts and before the dependency calls are done.

It may happen because there is a hop between native and managed thread in your code or in some of the components you use - e.g. in IIS (this one we should handle).

I'm afraid without the repro app we can't say for sure what's causing it.

**Comment by federicobarera** [comment] 2017-08-09 22:46
I can see why that could possibly happen due to the switch of threads, what is still unclear to me is why it regressed from 2.2 (where everything works fine for us) to 2.4.

I'll setup a sharepoint online website and send you the repro code asap.

Cheers

**Comment by kthayer424** [comment] 2017-10-17 20:02
I believe I have encountered this also after upgrading from 2.2 to 2.4. I'm running an MVC web app though and the dependency correlation is only lost on asynchronous HTTP dependency calls. I might have more info to help reproduce.

When stepping though the code line by line, it seems like the extra time doing that is helping the dependencies correlate. For example, here's a trimmed down request track and a remote http dependency call that look correct.

`{"name":"Microsoft.ApplicationInsights.Dev.REDACTEDKEY.Request","time":"2017-10-17T18:51:12.0876348Z","tags":{"ai.operation.parentId":"mM2Wv","ai.operation.name":"POST Forms [shortCode/version]","ai.operation.id":"tKEwM", ...}`

`{"name":"Microsoft.ApplicationInsights.Dev.REDACTEDKEY.RemoteDependency","time":"2017-10-17T18:53:08.9153624Z","tags":{"ai.operation.parentId":"|tKEwM.8b2af2b5_8b2af2b7_","ai.operation.name":"POST Forms [shortCode/version]","ai.operation.id":"tKEwM",...}`

Those share the same `ai.operation.id` value so everything looks correct in the portal. Now, if I let the calls run uninterrupted, the operation id on the remote dependency changes, for example:

`{"name":"Microsoft.ApplicationInsights.Dev.REDACTEDKEY.Request","time":"2017-10-17T18:56:23.7853581Z","tags":{"ai.operation.parentId":"RPqUE","ai.operation.name":"POST Forms [shortCode/version]","ai.operation.id":"UznKu",...}`

`{"name":"Microsoft.ApplicationInsights.Dev.REDACTEDKEY.RemoteDependency","time":"2017-10-17T18:56:24.7746957Z","tags":{"ai.operation.name":"POST Forms [shortCode/version]","ai.operation.id":"8b2af2d8-414b3a0487534431",...}}`

There's a couple things wrong here, `ai.operation.parentId` is missing entirely from the RemoteDependency and there's something else generating the `ai.operation.id` because it looks so different. However, this problem only affects HTTP-type remote dependency calls and from what I've seen only async calls. SQL calls (even async SQL calls) and traces look ok. Does that help narrow down the problem?

**Comment by kthayer424** [comment] 2017-10-17 20:47
I'll add that I see this problem about 99% of the time, not 100%. Occasionally, the http remote dependencies do get the right operation id and things link up right in the portal, but it's very rare.

**Comment by timvandenhof** [comment] 2017-11-10 12:50
Actually we are seeing issues from upgrading from 2.3.0 to 2.4.0. HttpClient calls seem not to be tracked as dependency since then. Other dependencies are being tracked fine.

Tried with 2.4.1 and 2.5.0-beta but same issue. Seen this happening on two applications so far. Still verifiying the issue on a smaller scale, if reproducible I consider creating a seperate issue. Might be related to what is going on here. This is on .NET 4.7 full framework in an Azure WebApp, and locally in 4.6.2 as well.

**Comment by SergeyKanzhelev** [comment] 2017-11-10 17:33
@timvandenhof - do you see dependency events not being correlated or not collected at all?

@zakimaksyutov noticed that some failed calls via HttpClient may not be collected. Is it the case? Or successful calls not collected as well?

CC @lmolkova explicitly.

**Comment by cijothomas** [comment] 2017-11-10 18:23
perfview is the easiest.
Another option is to add DiagnosticsTelemetryModule , and set it's verbosity to Verbose, and perhapds give a different ikey to get all logs sent to that ikey as trace.. (i can find an example if this approach is needed)

**Comment by lmolkova** [comment] 2017-11-10 19:38
@cijothomas, thanks for the help, Iet's try perfview

@timvandenhof 
Could you please also try to reproduce the problem with (`DisableDiagnosticSourceInstrumentation` set to false - by default)?

Please at the same time collect EventSource logs:
1. Download PerfView https://www.microsoft.com/en-us/download/details.aspx?id=28567
2. In PefrView, 
 - chose Collect->Collect from the menu 
 - expand "Advanced Options"
 - Uncheck all checked checkboxes
 - Add "Additional Provides": *Microsoft-ApplicationInsights-Extensibility-AppMapCorrelation-Web,*Microsoft-ApplicationInsights-Extensibility-DependencyCollector,*Microsoft-ApplicationInsights-WindowsServer-TelemetryChannel

![image](https://user-images.githubusercontent.com/2347409/32675057-670af048-c60a-11e7-91f4-cf0d5d0f495b.png)

- when you are ready to repro, click 'Start Collection'
- Try to repro (try several times, if it does not repro 100% of times)
- Click 'Stop Collection'
- Make sure at least one dependency was not tracked

Please send us back the etl file with captured events.

Thanks!

**Comment by SergeyKanzhelev** [comment] 2018-04-11 05:29
This issue is being tracked in separate repository now. Closing it here

**Closed by SergeyKanzhelev** 2018-04-11 05:29 UTC
