### ISSUE TITLE
APPINSIGHTS_JAVASCRIPT_ENABLED causes '500.53 URL rewrite module error with message Outbound rewrite rules cannot be applied when the content of the HTTP response is encoded ('gzip')'

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-Home#282] opened 2018-11-06 17:27 UTC
When using APPINSIGHTS_JAVASCRIPT_ENABLED = 'True' setting in the web app, AI appears to be applying dynamicCompressionBeforeCache even though the default rule should be set to not perform this.

From customer:

- It’s an MVC controller action response from an ApiController that returns a HttpResponseMessage
- It’s content type is text/html
- The controller action has been unchanged in over a year and has worked without any issues until the install of AI and the application of this outbound rule.
- We tried adding `<urlCompression dynamicCompressionBeforeCache='false' />` to our web.config but it made no difference
-- In fact, it looks like applicationHost.xdt already tries to do this itself with line
`<urlCompression dynamicCompressionBeforeCache='false' xdt:Transform='InsertOrAppendAttribute(Attribute='dynamicCompressionBeforeCache')'/>`

**Comment by MS-TimothyMothra** [comment] 2018-11-27 00:45
Seeing this issue get reported frequently.

@lmolkova had a good suggestion, that we make the `urlCompression` tag conditional. 

Until then, the workaround we're recommending is that customers add an xdttransform to their project to remove the unwanted properties from their applicationHost.
See: https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples

**Comment by lmolkova** [comment] 2018-11-27 03:02
Per my experiments, urlCompression is not modified by default. 
What makes the difference is having APPINSIGHTS_JAVASCRIPT_ENABLED  set to true. It does not change applicaitonHost.config, but changing value or removing the variable mitigates the issue.

**Comment by kevinburkett** [comment] 2019-03-04 17:32
Is there an ETA when this will get fixed?  It is preventing my team from getting diagnostic data from the browser.  This bug was filed 4 months ago.

**Comment by lmolkova** [comment] 2019-03-04 18:21
@kevinburkett  you can workaround the issue in your environment right now by removing  APPINSIGHTS_JAVASCRIPT_ENABLED  or setting it to false.

@cijothomas is working on permanent fix.

**Comment by cijothomas** [comment] 2019-03-05 15:32
@kevinburkett can you describe the issue you are facing ? Are you having issues in asp.net core app? Are you seeing partial html response? Or something else?

I have a fix deployed to mitigate the partial html response for asp.net core 2.0,2.1 apps.

**Comment by MS-TimothyMothra** [comment] 2019-03-06 23:14
@cijothomas when can we expect this fix in production? within a week?

**Comment by cijothomas** [comment] 2019-03-07 04:06
The fix was already deployed 2-3 weeks back.

**Comment by Shawson** [comment] 2019-04-17 08:26
Is this definitely confirmed as fixed?  We've seen this issue arising on our live site as recently as a week ago?  Having not found this GitHub issue, our only solution to stop the random UURL Rewrite errors on our static Angular html templates was to turn application insights collection level down to "Basic".

**Comment by cijothomas** [comment] 2019-04-17 14:10
@Shawson do you have set APPINSIGHTS_JAVASCRIPT_ENABLED to true?

**Comment by Shawson** [comment] 2019-04-18 08:28
I did; we've since set this to false and turned AI back to "recommended" last night and so far the issue seems to be resolved, which is great!

**Comment by cijothomas** [comment] 2019-04-18 15:57
@Shawson Glad to see it resolved for you. What was your application type - asp.net core 2.1 or 2.2?

**Comment by Shawson** [comment] 2019-04-24 08:31
No core- Just plain old MVC5 running under .net 4.7

**Comment by cijothomas** [comment] 2019-04-24 15:40
@Shawson then this issue is not fixed, and you need to workaround by setting APPINSIGHTS_JAVASCRIPT_ENABLED  to false.

**Comment by Shawson** [comment] 2019-04-25 10:36
Yes I'd thought as much; this is the workaround we have employed.

**Comment by cijothomas** [comment] 2019-04-25 14:43
Please note that this issue is NOT fixed.
https://github.com/Microsoft/ApplicationInsights-Home/issues/277 is fixed - which was about asp.net core apps getting partial html response.

**Comment by Mikhail-Pranovich** [comment] 2019-04-25 16:37
There is a confusion between two independent issues in this thread:
1. URL rewrite error. This is due to APPINSIGHTS_JAVASCRIPT_ENABLED=true and the content is encoded
    * this issue is not fixed, and the scenario is not supported yet. The workaround is to remove APPINSIGHTS_JAVASCRIPT_ENABLED from app settings. Unfortunately that means that if Javascript instrumentation required, the manual SDK reference is needed from the webpage [instructions](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#add-the-sdk-script-to-your-app-or-web-pages).
2. Partial response in .net core apps as mentioned by @lmolkova and @cijothomas 
    * this issue is fixed, but it is not related to current issue.

**Comment by TimothyMothra** [comment] 2020-04-08 00:13
I'm closing this ticket as out of date.
If you're still having issues, please reopen.

**Closed by TimothyMothra** 2020-04-08 00:13 UTC
Labels: prod:azrue-appservice-extension
