### ISSUE TITLE
The EmailService sample doesn't build

### ISSUE THREAD

**Issue by ivanz** [Microsoft/ApplicationInsights-Home#16] opened 2015-06-27 18:36 UTC
```
1>------ Build started: Project: MvcWebRole, Configuration: Debug Any CPU ------
1>  Restoring NuGet packages...
1>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
1>  All packages listed in packages.config are already installed.
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.ApplicationInsights.PersistenceChannel". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>  Consider app.config remapping of assembly "WebGrease, Culture=neutral, PublicKeyToken=31bf3856ad364e35" from Version "1.5.1.25624" [] to Version "1.5.2.14234" [C:\code\AzureEmailService\packages\WebGrease.1.5.2\lib\WebGrease.dll] to solve conflict and get rid of warning.
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="WebGrease" culture="neutral" publicKeyToken="31bf3856ad364e35" /><bindingRedirect oldVersion="0.0.0.0-1.5.2.14234" newVersion="1.5.2.14234" /></dependentAssembly></assemblyBinding>
1>C:\code\AzureEmailService\MvcWebRole\Controllers\MailingListController.cs(6,30,6,44): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)
1>C:\code\AzureEmailService\MvcWebRole\Controllers\MessageController.cs(6,30,6,44): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)
1>C:\code\AzureEmailService\MvcWebRole\Controllers\SubscribeAPI.cs(7,30,7,44): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)
1>C:\code\AzureEmailService\MvcWebRole\Controllers\SubscribeController.cs(5,30,5,44): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)
1>C:\code\AzureEmailService\MvcWebRole\Controllers\SubscriberController.cs(6,30,6,44): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)
1>C:\code\AzureEmailService\MvcWebRole\Controllers\UnsubscribeController.cs(5,30,5,44): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)
1>C:\code\AzureEmailService\MvcWebRole\Global.asax.cs(2,30,2,44): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)
1>C:\code\AzureEmailService\MvcWebRole\WebRole.cs(5,30,5,41): error CS0234: The type or namespace name 'Diagnostics' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)
1>C:\code\AzureEmailService\MvcWebRole\WebRole.cs(6,30,6,44): error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)
1>C:\code\AzureEmailService\MvcWebRole\WebRole.cs(12,28,12,42): error CS0246: The type or namespace name 'RoleEntryPoint' could not be found (are you missing a using directive or an assembly reference?)
2>------ Build started: Project: WorkerRoleA, Configuration: Debug Any CPU ------
3>------ Build started: Project: WorkerRoleB, Configuration: Debug Any CPU ------
2>  Restoring NuGet packages...
2>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
2>  All packages listed in packages.config are already installed.
3>  Restoring NuGet packages...
3>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
3>  All packages listed in packages.config are already installed.
3>CSC : error CS0006: Metadata file 'C:\code\AzureEmailService\MvcWebRole\bin\MvcWebRole.dll' could not be found
4>------ Build started: Project: AzureEmailService, Configuration: Debug Any CPU ------
4>C:\code\AzureEmailService\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets(225,5): warning : All projects referencing MvcWebRole.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
4>C:\code\AzureEmailService\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets(225,5): warning : All projects referencing WorkerRoleB.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
4>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Windows Azure Tools\2.6\Microsoft.WindowsAzure.targets(1329,5): error : WAT070 : The referenced assembly C:\code\AzureEmailService\MvcWebRole\bin\MvcWebRole.dll was not found. Please make sure to build the role project that produces this assembly before building this Microsoft Azure Cloud Service Project.
4>Done building project "AzureEmailService.ccproj" -- FAILED.
4>
4>Build FAILED.
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by SergKanz** [comment] 2015-06-29 15:45
Hi @SoubhagyaDash . In this [packages.config](https://github.com/Microsoft/ApplicationInsights-Home/blob/1aa80b18e9732f8d42bcec45ad308a4d87c3a7eb/Samples/AzureEmailService/MvcWebRole/packages.config) you have a NuGet reference to ```<package id="Microsoft.ApplicationInsights.Web.TelemetryChannel" version="0.17.0" targetFramework="net45" />``` However in [MvcWebRole.csproj](https://github.com/Microsoft/ApplicationInsights-Home/blob/1aa80b18e9732f8d42bcec45ad308a4d87c3a7eb/Samples/AzureEmailService/MvcWebRole/MvcWebRole.csproj) you still refer to ```PersistenceChannel```. Can you please fix it?

@ivanz, this issue is easy to fix if you need a fix faster - just replace the reference to the reference to ```Microsoft.ApplicationInsights.Web.Channel```. The root cause of this problem is that we split one channel that was used for both - devices and server scenarios to two separate channels optimized for specific scenarios. It seems that old references are just leftovers of this separation. Sorry for this.

**Comment by SoubhagyaDash** [comment] 2015-06-29 22:06
Fixed with https://github.com/Microsoft/ApplicationInsights-Home/pull/17

**Closed by SoubhagyaDash** 2015-06-29 22:06 UTC
